import "dotenv/config";
import express from "express";
import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { generateGameWithOpenAI } from "./openai";
import { assertHasRequiredHashtag, injectShareWidget } from "./shareLink";
import { validateExportZipRequest, validateGeneratedPayload, validateGenerateRequest } from "./validators";
import { createZip } from "./zip";

const app = express();
const port = Number(process.env.PORT ?? 8787);
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const clientDist = path.resolve(__dirname, "../../../client/dist");

app.use(express.json({ limit: "1mb" }));

app.get("/api/health", (_req, res) => {
  res.json({ ok: true, service: "minigame-tcool-api" });
});

app.post("/api/generate", async (req, res) => {
  try {
    const input = validateGenerateRequest(req.body);

    let generated: unknown;
    let lastError: unknown;

    for (let attempt = 0; attempt < 2; attempt += 1) {
      try {
        generated = await generateGameWithOpenAI(input);
        const payload = validateGeneratedPayload(generated);
        const bundle = injectShareWidget(payload.bundle, payload.title);
        assertHasRequiredHashtag(bundle);
        const gameId = randomUUID();

        res.json({
          gameId,
          title: payload.title,
          description: payload.description,
          bundle
        });
        return;
      } catch (error) {
        lastError = error;
      }
    }

    throw lastError;
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown generation error.";
    res.status(400).json({ error: message });
  }
});

app.post("/api/export-zip", (req, res) => {
  try {
    const payload = validateExportZipRequest(req.body);

    const htmlDocument = [
      "<!doctype html>",
      "<html lang=\"en\">",
      "<head>",
      "  <meta charset=\"UTF-8\" />",
      "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
      `  <title>${payload.title.replace(/[<>]/g, "")}</title>`,
      '  <link rel="stylesheet" href="style.css" />',
      "</head>",
      "<body>",
      payload.bundle.html,
      '  <script src="game.js"></script>',
      "</body>",
      "</html>"
    ].join("\n");

    const readme = [
      `# ${payload.title}`,
      "",
      payload.description,
      "",
      "## Run",
      "Open index.html in your browser.",
      "",
      "Generated by minigame-tcool."
    ].join("\n");

    const zip = createZip([
      { name: "index.html", data: htmlDocument },
      { name: "style.css", data: payload.bundle.css },
      { name: "game.js", data: payload.bundle.js },
      { name: "README.txt", data: readme }
    ]);

    const safeName = payload.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "mini-game";
    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename=\"${safeName}.zip\"`);
    res.send(zip);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown export error.";
    res.status(400).json({ error: message });
  }
});

if (existsSync(clientDist)) {
  app.use(express.static(clientDist));
  app.get("*", (req, res, next) => {
    if (req.path.startsWith("/api/")) {
      next();
      return;
    }
    res.sendFile(path.join(clientDist, "index.html"));
  });
}

app.listen(port, () => {
  const mock = (process.env.MOCK_MODE ?? "").toLowerCase().trim();
  const mockEnabled = mock === "1" || mock === "true" || mock === "yes" || mock === "on" || !process.env.OPENAI_API_KEY;
  const mode = mockEnabled ? "mock" : "openai";
  console.log(`minigame-tcool server listening on http://localhost:${port} (mode: ${mode})`);
});
